package:
  name: conda-env-spec-v2
  {% if GIT_DESCRIBE_TAG is defined and GIT_BUILD_STR is defined %}
  version: {{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}
  {% else %}
  version: 0.0.0dev0
  {% endif %}

source:
  # git_url only captures committed code
  git_url: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python 3.10
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.10
    - conda >=23.9.0
    - tomli >=2.0.1
    - tomli-w

test:
  requires:
    - python 3.10
  imports:
    - conda_env_spec_v2

about:
  home: https://github.com/conda-incubator/conda-env-spec-v2
  license: MIT AND BSD-3-Clause
  license_file: LICENSE
  summary: A V2 environment specification for conda.
  dev_url: https://github.com/conda-incubator/conda-env-spec-v2
