package:
  name: conda-declarative
  {% if GIT_DESCRIBE_TAG is defined and GIT_BUILD_STR is defined %}
  version: {{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}
  {% else %}
  version: 0.0.0dev0
  {% endif %}

source:
  # git_url only captures committed code
  git_url: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python 3.10
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - python >=3.10
    - conda >=23.9.0
    - tomli >=2.0.1
    - tomli-w

test:
  requires:
    - python 3.10
  imports:
    - conda_declarative
    - conda_declarative.apply
    - conda_declarative.edit
    - conda_declarative.cli
  commands:
    - conda edit --help
    - conda apply --help

about:
  home: https://github.com/conda-incubator/conda-declarative
  license: MIT AND BSD-3-Clause
  license_file: LICENSE
  summary: Declarative workflows for conda environment handling.
  dev_url: https://github.com/conda-incubator/conda-declarative
